### ISSUE TITLE
Coexistence with konstraint

### ISSUE THREAD

**Issue by chr-b** [clover/gatekeeper-conftest#1]
Hi,

I have played with this plugin and found it to be useful for my use case. Great job!

I have an observation though, regarding the two features you provide:
1. Transform input object to input.review
2. Transform file with input parameters from a separate file to input.parameters

The first one is already addressed by [konstraint](https://github.com/plexsystems/konstraint), thereby allowing to use the same policies with conftest and Gatekeeper. 

But what konstraint is missing is the second feature. It is currently not possible to easily parameterize policies and use them with both conftest and Gatekeeper.
On the other hand, gatekeeper-conftest supports executing parameterized policies with conftest, by using the `--parameters` flag.

I am therefore wondering if you have any plans to more closely integrate with konstraint?

**Comment by anush-cr** [comment]
Hi @chr-b,

I'm glad you found this plugin useful. There is currently no planned support for konstraint but I can look into this some more and add support for it if it is straight forward.

Are you looking to run the plugin against the konstraint rego policies or the generated gatekeeper constraint templates produced when you run `konstraint create`?

**Comment by chr-b** [comment]
Hi @anush-cr ,

it would be useful to use this plugin to execute conftest rego policies that utilize the konstraint rego library (e.g. [core.rego](https://github.com/plexsystems/konstraint/blob/main/examples/lib/core.rego)).

**Comment by anush-cr** [comment]
@chr-b,

You should be able to use this plugin with konstraint as well by providing a parameters file via `--parameters` flag. 

For example, below I've provided the labels parameter value for the [required-labels konstraint policy](https://github.com/plexsystems/konstraint/blob/main/examples/required-labels/src.rego) 

```
$ cat example/parameters.yaml 
parameters:
  labels: ["owner"]

$ conftest gatekeeper --parameters example/parameters.yaml ./example/k8s_app.yaml -- --policy ../konstraint/examples/ --namespace required_labels
FAIL - .gatekeeper-conftest/ReplicaSet_nginx-deployment.json - required_labels - P0002: ReplicaSet/nginx-deployment: Missing required labels: {"owner"}
FAIL - .gatekeeper-conftest/Deployment_nginx-deployment.json - required_labels - P0002: Deployment/nginx-deployment: Missing required labels: {"owner"}
FAIL - .gatekeeper-conftest/Job_hello.json - required_labels - P0002: Job/hello: Missing required labels: {"owner"}
FAIL - .gatekeeper-conftest/CronJob_hello.json - required_labels - P0002: CronJob/hello: Missing required labels: {"owner"}
FAIL - .gatekeeper-conftest/DaemonSet_fluentd-elasticsearch.json - required_labels - P0002: DaemonSet/fluentd-elasticsearch: Missing required labels: {"owner"}
FAIL - .gatekeeper-conftest/Service_my-service.json - required_labels - P0002: Service/my-service: Missing required labels: {"owner"}

11 tests, 5 passed, 0 warnings, 6 failures, 0 exceptions
Error: execute plugin: plugin exec: exit status 3
```
